modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0-or-later"
[[mods]]
modId="reforgedplaymod"
version="${version}"
displayName="ReForgedPlay Mod"
displayTest = "IGNORE_SERVER_VERSION"
authors="CrushedPixel, johni0702, Ferri_Arnus"
description='''
A Mod which allows you to record, replay and share your Minecraft experience.
'''

[[dependencies.reforgedplaymod]]
modId = "forge"
mandatory= true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reforgedplaymod]]
modId = "minecraft"
mandatory= true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "mixins.compat.mapwriter.replaymod.json"

[[mixins]]
config = "mixins.compat.shaders.replaymod.json"

[[mixins]]
config = "mixins.core.replaymod.json"

[[mixins]]
config = "mixins.extras.playeroverview.replaymod.json"

[[mixins]]
config = "mixins.jgui.json"

[[mixins]]
config = "mixins.nonmmlauncher.replaymod.json"

[[mixins]]
config = "mixins.recording.replaymod.json"

[[mixins]]
config = "mixins.render.blend.replaymod.json"

[[mixins]]
config = "mixins.render.replaymod.json"

[[mixins]]
config = "mixins.replay.replaymod.json"

[[mods]]
modId="replaymod"
version="${version}"
displayName="Replay Mod"
license="GPL-3.0-or-later"
displayTest = "IGNORE_SERVER_VERSION"
logoFile="assets/replaymod/favicon_logo.png"
authors="CrushedPixel, johni0702"
description='''
A Mod which allows you to record, replay and share your Minecraft experience.
'''
